<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cb6bc24b-c9bd-4b27-b02d-5d2b2526704b</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EncheresPredict.Application\EncheresPredict.Application.csproj" />
    <ProjectReference Include="..\EncheresPredict.Infrastructure\EncheresPredict.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
  </ItemGroup>
</Project>
